find_package(HDF5 REQUIRED)

add_extra_cmake_args(
  -DHDF5_C_LIBRARY:FILEPATH=${HDF5_C_LIBRARY}
  -DHDF5_HL_LIBRARY:FILEPATH=${HDF5_HL_LIBRARY}
  -DHDF5_LIBRARY:FILEPATH=${HDF5_LIBRARY}
  -DHDF5_INCLUDE_DIRS:PATH=${HDF5_INCLUDE_DIRS})
