find_package(LAPACK REQUIRED)
set(BLAS_LIBRARIES ${BLAS_LIBRARIES} CACHE INTERNAL "" FORCE)
set(LAPACK_LIBRARIES ${LAPACK_LIBRARIES} CACHE INTERNAL "" FORCE)

add_extra_cmake_args(
  -DBLAS_LIBRARIES=${BLAS_LIBRARIES}
  -DBLAS_LINKER_FLAGS=${BLAS_LINKER_FLAGS}
  -DLAPACK_LIBRARIES=${LAPACK_LIBRARIES}
  -DLAPACK_LINKER_FLAGS=${LAPACK_LINKER_FLAGS}
)
