# we need to launch python with the right environment so that the shared
# libraries are loaded correctly.
set(ENV{LD_LIBRARY_PATH} "${PREFIX}/lib:$ENV{LD_LIBRARY_PATH}")
message("COMMAND == ${PREFIX}/bin/python ${SOURCE_DIR}/setup.py install")
execute_process(COMMAND
  ${PREFIX}/bin/python setup.py install --prefix=${PREFIX}
  WORKING_DIRECTORY ${SOURCE_DIR}
  RESULT_VARIABLE rv)

if(NOT "${rv}" STREQUAL "0")
  message(FATAL_ERROR "numpy.install failed")
endif()
