find_package(TBB REQUIRED)

add_extra_cmake_args(
  -DTBB_INCLUDE_DIRS:PATH=${TBB_INCLUDE_DIRS}
  -DTBB_LIBRARIES:PATH=${TBB_LIBRARIES}
  -DTBB_MALLOC_INCLUDE_DIRS:PATH=${TBB_MALLOC_INCLUDE_DIRS}
  -DTBB_MALLOC_LIBRARY:FILEPATH=${TBB_MALLOC_LIBRARIES}
)
